[project]
name = "my-fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.5",
    "pyjwt>=2.14.0",
    "redis>=8.1.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
my-fastapi-project = "my_fastapi_project:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[dependency-groups]
dev = [
    "fakeredis>=2.38.0",
    "pytest>=9.1.1",
]

[tool.ruff.lint]
select = ["E", "F", "I"] # I就是import排序规则，必须保留
unfixable = [
    "F401", # 禁止自动修复【未使用import】，不会删import，但仍然画波浪线提醒
    "F841" # 如果你想：未使用变量也不要自动删除，可以打开这行注释
]
